services:
  postgres:
    image: postgres:13
    container_name: pg_test
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./internal/pkg/db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  avito-app:
    image: avito-app
    container_name: avito-app
    depends_on:
     - postgres
    command:
      - ./avito-app
    ports:
      - "3001:3001"