services:
  postgres:
    image: postgres:13
    container_name: pg_test
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"